language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing to install.."

before_script:
  - echo "no tests to run for now"

script:
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  
  - docker tag reverseproxy henry2020/reverseproxy:latest
  - docker tag udagram-api-user henry2020/udagram-frontend:latest
  - docker tag udagram-api-feed henry2020/udagram-api-feed:v1
  - docker tag udagram-api-user henry2020/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push henry2020/reverseproxy:latest
  - docker push henry2020/udagram-frontend:latest
  - docker push henry2020/udagram-api-feed:v1
  - docker push henry2020/udagram-api-user:v1

