apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-app
  labels:
    app: frontend-app
spec:
  ports:
  - port: 8100
    protocol: TCP
  selector:
    run: frontend-app
  type: ClusterIP

  
  