apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-app
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend
        image: henry2020/udagram-frontend:v4
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "150m"
            memory: "300Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
      restartPolicy: Always
      
