apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: henry2020/reverseproxy:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      restartPolicy: Always